<P style="FONT-SIZE: 14px; BORDER-TOP: #7f8c8d 1px solid; FONT-FAMILY: 'Segoe UI', Arial, sans-serif; BORDER-RIGHT: #7f8c8d 1px solid; BORDER-BOTTOM: #7f8c8d 1px solid; COLOR: #dcdde1; PADDING-BOTTOM: 25px; PADDING-TOP: 25px; PADDING-LEFT: 25px; BORDER-LEFT: #f39c12 6px solid; LINE-HEIGHT: 1.6; PADDING-RIGHT: 25px; BACKGROUND-COLOR: #2f3640">
<DIV style="MARGIN-BOTTOM: 25px; BORDER-BOTTOM: #f39c12 2px solid; PADDING-BOTTOM: 15px">
<H1 style="FONT-SIZE: 24px; TEXT-TRANSFORM: uppercase; COLOR: #f39c12; MARGIN: 0px; LETTER-SPACING: 1px">FLASH: OPERATION KOKKO</H1>
<P style="FONT-SIZE: 18px; COLOR: #a4b0be; FONT-STYLE: italic; MARGIN: 5px 0px 0px">AUTHENTICATION CODE: <B>"KOKKO PALAA"</B></P></DIV>
<DIV style="MARGIN-BOTTOM: 25px; BACKGROUND: #c23616; COLOR: #f5f6fa; PADDING-BOTTOM: 20px; PADDING-TOP: 20px; PADDING-LEFT: 20px; BORDER-LEFT: #e84118 6px solid; PADDING-RIGHT: 20px; border-radius: 4px">
<H3 style="FONT-SIZE: 20px; TEXT-TRANSFORM: uppercase; MARGIN: 0px 0px 10px">EXECUTIVE EXECUTION ORDER</H3>
<P style="FONT-SIZE: 17px; FONT-WEIGHT: bold; MARGIN: 0px">ALL AIR ASSETS ARE ORDERED TO VACATE MAIN OPERATING BASES (MOB) IMMEDIATELY. THE BONFIRE IS LIT.</P></DIV>
<DIV style="MARGIN-BOTTOM: 25px"><IMG style="MAX-WIDTH: 500px; BORDER-TOP: #57606f 1px solid; HEIGHT: auto; BORDER-RIGHT: #57606f 1px solid; WIDTH: 100%; BORDER-BOTTOM: #57606f 1px solid; BORDER-LEFT: #57606f 1px solid; border-radius: 4px" src="http://www.mypic.com/picture.jpg"> 
<P style="FONT-SIZE: 14px; MARGIN-TOP: 8px; COLOR: #7f8c8d">FIG 1. STRATEGIC THREAT VECTOR: RF LONG-RANGE SAM COVERAGE (A2/AD).</P></DIV>
<H2 style="FONT-SIZE: 20px; BORDER-BOTTOM: #57606f 1px solid; TEXT-TRANSFORM: uppercase; COLOR: #f39c12; PADDING-BOTTOM: 8px">1. DISPERSAL DIRECTIVE</H2>
<P style="FONT-SIZE: 17px">ALL SQUADRONS SHALL INITIATE <B>EMERGENCY SCRAMBLE</B>. TRANSITION TO PRE-DESIGNATED <B>HIGHWAY STRIPS (HWS)</B> AND REMOTE PROVINCIAL AIRFIELDS IMMEDIATELY. THE ENEMY SEEKS TO DESTROY US IN OUR NESTS; WE SHALL NOT BE THERE TO RECEIVE THE BLOW.</P>
<H2 style="FONT-SIZE: 20px; BORDER-BOTTOM: #57606f 1px solid; TEXT-TRANSFORM: uppercase; COLOR: #f39c12; PADDING-BOTTOM: 8px">2. RECOVERY &amp; QUICK TURNAROUND (QTA)</H2>
<UL style="FONT-SIZE: 17px; PADDING-LEFT: 25px">
<LI style="MARGIN-BOTTOM: 10px"><B>LANDING:</B> TOUCHDOWN AT ASSIGNED FARP/PROVINCIAL SITES ASAP.</LI>
<LI style="MARGIN-BOTTOM: 10px"><B>REARM/REFUEL:</B> EXECUTE <B>"QUICK TURNAROUND"</B> PROCEDURES UPON ENGINE SHUTDOWN. HOT-PIT REFUELING AUTHORIZED.</LI>
<LI style="MARGIN-BOTTOM: 10px"><B>READINESS:</B> UPON COMPLETION OF QTA, ALL AIRFRAMES SHALL MAINTAIN <B>2-MINUTE ALERT STATUS</B> (STRS).</LI></UL>
<DIV style="FONT-SIZE: 17px; BACKGROUND: #353b48; MARGIN-TOP: 25px; COLOR: #bdc3c7; PADDING-BOTTOM: 20px; FONT-STYLE: italic; PADDING-TOP: 20px; PADDING-LEFT: 20px; BORDER-LEFT: #f39c12 4px solid; PADDING-RIGHT: 20px; border-radius: 4px">"Let the iron rain fall upon empty concrete. While the adversary celebrates the destruction of our ghosts, the <B>Kokko</B> gathers its strength in the shadows of the forest. We do not flee to hide; we disperse to survive, and we survive to strike back with a fury they cannot anticipate. When they think us broken, we shall rise from the trees." </DIV>
<DIV style="FONT-SIZE: 16px; MARGIN-TOP: 30px; FONT-WEIGHT: bold; COLOR: #f39c12; TEXT-ALIGN: right">CHOD FINLAND / COMMANDER FINAF<BR>SECRET // REL NATO // FLASH </DIV>
<P></P>